In [1]:
!git clone https://github.com/shaonkhalifa/iot-anomaly-ml-service.git

Cloning into 'iot-anomaly-ml-service'...
remote: Enumerating objects: 76, done.
remote: Counting objects: 100% (76/76), done.
remote: Compressing objects: 100% (61/61), done.
remote: Total 76 (delta 13), reused 74 (delta 11), pack-reused 0 (from 0)
Receiving objects: 100% (76/76), 1.94 MiB | 5.64 MiB/s, done.
Resolving deltas: 100% (13/13), done.

In [2]:
%cd iot-anomaly-ml-service
!ls

/content/iot-anomaly-ml-service
app   Dockerfile	       README.md	 results       train.py
data  generate_sample_data.py  requirements.txt  saved_models

In [3]:
!pip install -r requirements.txt

Collecting flask==3.0.3 (from -r requirements.txt (line 1))
  Downloading flask-3.0.3-py3-none-any.whl.metadata (3.2 kB)
Collecting flask-cors==5.0.0 (from -r requirements.txt (line 2))
  Downloading Flask_Cors-5.0.0-py2.py3-none-any.whl.metadata (5.5 kB)
Requirement already satisfied: pandas>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from -r requirements.txt (line 3)) (2.2.2)
Requirement already satisfied: numpy>=1.24.0 in /usr/local/lib/python3.12/dist-packages (from -r requirements.txt (line 4)) (2.0.2)
Requirement already satisfied: scikit-learn>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from -r requirements.txt (line 5)) (1.6.1)
Requirement already satisfied: matplotlib>=3.7.0 in /usr/local/lib/python3.12/dist-packages (from -r requirements.txt (line 6)) (3.10.0)
Requirement already satisfied: seaborn>=0.12.0 in /usr/local/lib/python3.12/dist-packages (from -r requirements.txt (line 7)) (0.13.2)
Requirement already satisfied: joblib>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from -r requirements.txt (line 8)) (1.5.3)
Collecting gunicorn==22.0.0 (from -r requirements.txt (line 9))
  Downloading gunicorn-22.0.0-py3-none-any.whl.metadata (4.4 kB)
Requirement already satisfied: Werkzeug>=3.0.0 in /usr/local/lib/python3.12/dist-packages (from flask==3.0.3->-r requirements.txt (line 1)) (3.1.8)
Requirement already satisfied: Jinja2>=3.1.2 in /usr/local/lib/python3.12/dist-packages (from flask==3.0.3->-r requirements.txt (line 1)) (3.1.6)
Requirement already satisfied: itsdangerous>=2.1.2 in /usr/local/lib/python3.12/dist-packages (from flask==3.0.3->-r requirements.txt (line 1)) (2.2.0)
Requirement already satisfied: click>=8.1.3 in /usr/local/lib/python3.12/dist-packages (from flask==3.0.3->-r requirements.txt (line 1)) (8.3.2)
Requirement already satisfied: blinker>=1.6.2 in /usr/local/lib/python3.12/dist-packages (from flask==3.0.3->-r requirements.txt (line 1)) (1.9.0)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from gunicorn==22.0.0->-r requirements.txt (line 9)) (26.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas>=2.0.0->-r requirements.txt (line 3)) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas>=2.0.0->-r requirements.txt (line 3)) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas>=2.0.0->-r requirements.txt (line 3)) (2026.1)
Requirement already satisfied: scipy>=1.6.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn>=1.3.0->-r requirements.txt (line 5)) (1.16.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn>=1.3.0->-r requirements.txt (line 5)) (3.6.0)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.7.0->-r requirements.txt (line 6)) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.7.0->-r requirements.txt (line 6)) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.7.0->-r requirements.txt (line 6)) (4.62.1)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.7.0->-r requirements.txt (line 6)) (1.5.0)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.7.0->-r requirements.txt (line 6)) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.7.0->-r requirements.txt (line 6)) (3.3.2)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from Jinja2>=3.1.2->flask==3.0.3->-r requirements.txt (line 1)) (3.0.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas>=2.0.0->-r requirements.txt (line 3)) (1.17.0)
Downloading flask-3.0.3-py3-none-any.whl (101 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 101.7/101.7 kB 3.7 MB/s eta 0:00:00
Downloading Flask_Cors-5.0.0-py2.py3-none-any.whl (14 kB)
Downloading gunicorn-22.0.0-py3-none-any.whl (84 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 84.4/84.4 kB 5.7 MB/s eta 0:00:00
Installing collected packages: gunicorn, flask, flask-cors
  Attempting uninstall: flask
    Found existing installation: Flask 3.1.3
    Uninstalling Flask-3.1.3:
      Successfully uninstalled Flask-3.1.3
Successfully installed flask-3.0.3 flask-cors-5.0.0 gunicorn-22.0.0

In [4]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [5]:
DATA_PATH = '/content/drive/MyDrive/data/train_data.csv'

In [6]:
df = pd.read_csv('train_data.csv')

NameError: name 'pd' is not defined

In [8]:
import pandas as pd
df = pd.read_csv('/content/drive/MyDrive/data/train_data.csv')

In [9]:
!git pull origin main

remote: Enumerating objects: 5, done.
remote: Counting objects: 100% (5/5), done.
remote: Compressing objects: 100% (1/1), done.
remote: Total 3 (delta 2), reused 3 (delta 2), pack-reused 0 (from 0)
Unpacking objects: 100% (3/3), 406 bytes | 406.00 KiB/s, done.
From https://github.com/shaonkhalifa/iot-anomaly-ml-service
 * branch            main       -> FETCH_HEAD
   38f0c43..07d601a  main       -> origin/main
Updating 38f0c43..07d601a
Fast-forward
 train.py | 8 ++++++--
 1 file changed, 6 insertions(+), 2 deletions(-)

In [10]:
!git status

On branch main
Your branch is up to date with 'origin/main'.

nothing to commit, working tree clean

In [11]:
!ls

app   Dockerfile	       README.md	 results       train.py
data  generate_sample_data.py  requirements.txt  saved_models

In [14]:
import os

if 'COLAB_GPU' in os.environ:
    DATA_DIR = "/content/drive/MyDrive/data"
else:
    BASE_DIR = os.path.dirname(os.path.abspath("__file__"))
    DATA_DIR = os.path.join(BASE_DIR, "..", "data")

In [15]:
print(DATA_DIR)

/content/drive/MyDrive/data

In [16]:
import os
print(os.path.exists(DATA_DIR))

True

In [17]:
import pandas as pd

df = pd.read_csv(f"{DATA_DIR}/train_data.csv")
df.head()

,RmsStationId,NodeId,TenantId,TagId,MobileNumber,LogIntValue,LogFloatValue,ServerTime,LogTime,log_hour,...,LogType_5,LogType_6,LogSubType_1,LogSubType_2,LogSubType_3,LogSubType_4,LogSubType_6,LogSubType_7,LogSubType_8,LogSubType_10
0,5724,42,0,0,0,0,32.826752,2026-01-02 10:40:06,2026-01-02 10:40:02,10,...,False,False,True,False,False,False,False,False,False,False
1,5227,27,9,0,1767258645,0,35.989456,2026-01-02 04:14:34,2026-01-02 04:14:27,4,...,False,False,False,False,True,False,False,False,False,False
2,6998,27,9,0,1767292885,2,0.000000,2026-01-02 00:42:00,2026-01-02 00:41:57,0,...,False,False,False,False,False,True,False,False,False,False
3,3263,39,0,0,0,0,53.492764,2026-01-02 06:40:02,2026-01-02 06:40:07,6,...,False,True,True,False,False,False,False,False,False,False
4,3427,89,25,0,1766642553,0,12.340129,2026-01-01 03:51:15,2026-01-01 03:51:07,3,...,False,False,False,True,False,False,False,False,False,False

In [18]:
df.info()
df.isnull().sum()
df.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500000 entries, 0 to 499999
Data columns (total 27 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   RmsStationId    500000 non-null  int64
 1   NodeId          500000 non-null  int64
 2   TenantId        500000 non-null  int64
 3   TagId           500000 non-null  int64
 4   MobileNumber    500000 non-null  int64
 5   LogIntValue     500000 non-null  int64
 6   LogFloatValue   500000 non-null  float64
 7   ServerTime      500000 non-null  object
 8   LogTime         500000 non-null  object
 9   log_hour        500000 non-null  int64
 10  log_dayofweek   500000 non-null  int64
 11  is_night        500000 non-null  int64
 12  time_delay_sec  500000 non-null  float64
 13  true_label      0 non-null       float64
 14  LogType_1       500000 non-null  bool
 15  LogType_2       500000 non-null  bool
 16  LogType_4       500000 non-null  bool
 17  LogType_5       500000 non-null  bool
 18  LogType_6       500000 non-null  bool
 19  LogSubType_1    500000 non-null  bool
 20  LogSubType_2    500000 non-null  bool
 21  LogSubType_3    500000 non-null  bool
 22  LogSubType_4    500000 non-null  bool
 23  LogSubType_6    500000 non-null  bool
 24  LogSubType_7    500000 non-null  bool
 25  LogSubType_8    500000 non-null  bool
 26  LogSubType_10   500000 non-null  bool
dtypes: bool(13), float64(3), int64(9), object(2)
memory usage: 59.6+ MB

,RmsStationId,NodeId,TenantId,TagId,MobileNumber,LogIntValue,LogFloatValue,ServerTime,LogTime,log_hour,...,LogType_5,LogType_6,LogSubType_1,LogSubType_2,LogSubType_3,LogSubType_4,LogSubType_6,LogSubType_7,LogSubType_8,LogSubType_10
0,5724,42,0,0,0,0,32.826752,2026-01-02 10:40:06,2026-01-02 10:40:02,10,...,False,False,True,False,False,False,False,False,False,False
1,5227,27,9,0,1767258645,0,35.989456,2026-01-02 04:14:34,2026-01-02 04:14:27,4,...,False,False,False,False,True,False,False,False,False,False
2,6998,27,9,0,1767292885,2,0.000000,2026-01-02 00:42:00,2026-01-02 00:41:57,0,...,False,False,False,False,False,True,False,False,False,False
3,3263,39,0,0,0,0,53.492764,2026-01-02 06:40:02,2026-01-02 06:40:07,6,...,False,True,True,False,False,False,False,False,False,False
4,3427,89,25,0,1766642553,0,12.340129,2026-01-01 03:51:15,2026-01-01 03:51:07,3,...,False,False,False,True,False,False,False,False,False,False

In [19]:
!pip install numpy pandas scikit-learn matplotlib seaborn joblib

Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (2.0.2)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.12/dist-packages (1.6.1)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.12/dist-packages (3.10.0)
Requirement already satisfied: seaborn in /usr/local/lib/python3.12/dist-packages (0.13.2)
Requirement already satisfied: joblib in /usr/local/lib/python3.12/dist-packages (1.5.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2026.1)
Requirement already satisfied: scipy>=1.6.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (1.16.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (3.6.0)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (4.62.1)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (1.5.0)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (26.0)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (3.3.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [20]:
import os

print(os.path.exists("/content/drive/MyDrive/data/train_data.csv"))
print(os.path.exists("/content/drive/MyDrive/data/test_data.csv"))

True
True

In [21]:
!python train.py

=================================================================
  IoT Anomaly Detection - Training Pipeline
  (Hierarchical Event-Log Schema)
=================================================================

[1/5] Loading & preprocessing TRAINING data:
      /content/drive/MyDrive/data/train_data.csv

  --------------------------------------------------
  Stage 1: Load
  --------------------------------------------------
    Loaded 500000 rows × 27 columns

  --------------------------------------------------
  Stage 2: Clean
  --------------------------------------------------
    Dropped fully empty rows: 0
    Dropped duplicate rows:   0
    One-hot columns detected: 13 (['LogType_1', 'LogType_2', 'LogType_4', 'LogType_5', 'LogType_6', 'LogSubType_1', 'LogSubType_2', 'LogSubType_3', 'LogSubType_4', 'LogSubType_6', 'LogSubType_7', 'LogSubType_8', 'LogSubType_10'])

  --------------------------------------------------
  Stage 3: Timestamps
  --------------------------------------------------
    LogTime parsed. Invalid (unparseable): 0
    ServerTime parsed. Invalid: 0

  --------------------------------------------------
  Stage 4: Missing Values
  --------------------------------------------------
    Imputation complete. Remaining NaN in signals: 0

  --------------------------------------------------
  Stage 5: Statistical Outlier Flags (Context-Aware IQR)
  --------------------------------------------------
    'LogIntValue' context-aware IQR -> 0 total flagged across 5 groups
    'LogFloatValue' context-aware IQR -> 5984 total flagged across 5 groups

  --------------------------------------------------
  Stage 6: Scale
  --------------------------------------------------
    StandardScaler fitted and saved -> 21 features

  ==================================================
  CLEANING SUMMARY
  ==================================================
    Raw rows              : 500000
    Duplicate rows removed: 0
    Empty rows removed    : 0
    Final rows            : 500000
    Features for model    : 21
    Feature list          : ['LogIntValue', 'LogFloatValue', 'log_hour', 'log_dayofweek', 'is_night', 'time_delay_sec', 'LogType_1', 'LogType_2', 'LogType_4', 'LogType_5', 'LogType_6', 'LogSubType_1', 'LogSubType_10', 'LogSubType_2', 'LogSubType_3', 'LogSubType_4', 'LogSubType_6', 'LogSubType_7', 'LogSubType_8', 'flag_iqr_LogFloatValue', 'flag_iqr_LogIntValue']
  ==================================================

      Clean rows : 500000 / 500000
      Removed    : 0 rows
      Features   : 21

[2/5] Training models …
  Training Isolation Forest …
  [OK] Isolation Forest saved: /content/iot-anomaly-ml-service/app/models/../../saved_models/isolation_forest.pkl
  Training One-Class SVM …
    [!] Dataset large (500000 rows).
    [!] Sampling down to 50,000 rows to prevent Google Colab RAM crash.
  [OK] One-Class SVM saved: /content/iot-anomaly-ml-service/app/models/../../saved_models/one_class_svm.pkl
  Training K-Means …
  [OK] K-Means saved: /content/iot-anomaly-ml-service/app/models/../../saved_models/kmeans.pkl
  [OK] K-Means threshold: 4.5254

[3/5] Evaluating on TEST data:
      /content/drive/MyDrive/data/test_data.csv
      Test rows: 100000
      Ground truth: 95000 normal, 5000 anomaly

  -- Isolation Forest --
     Total readings : 100000
     Normal         : 92951  (93.0%)
     Anomalies      : 7049  (7.0%)
     Score mean     : 0.0778
     Score std      : 0.0449

     -- Isolation Forest: Supervised Metrics --
     Accuracy  : 0.9281
     Precision : 0.3446
     Recall    : 0.4858
     F1 Score  : 0.4032
     Confusion Matrix:
       TN= 90380  FP=  4620
       FN=  2571  TP=  2429
     [OK] Metrics saved -> /content/iot-anomaly-ml-service/app/../results/isolation_forest_metrics.txt
     [OK] Confusion matrix  -> /content/iot-anomaly-ml-service/app/../results/isolation_forest_confusion_matrix.png
  [OK] Time-series plot saved -> /content/iot-anomaly-ml-service/app/../results/isolation_forest_LogFloatValue_timeseries.png
  [OK] Score distribution   -> /content/iot-anomaly-ml-service/app/../results/isolation_forest_score_distribution.png
  [OK] Scatter plot         -> /content/iot-anomaly-ml-service/app/../results/isolation_forest_scatter.png

  -- One-Class SVM --
     Total readings : 100000
     Normal         : 92704  (92.7%)
     Anomalies      : 7296  (7.3%)
     Score mean     : 22.2856
     Score std      : 51.3521

     -- One-Class SVM: Supervised Metrics --
     Accuracy  : 0.9244
     Precision : 0.3246
     Recall    : 0.4736
     F1 Score  : 0.3852
     Confusion Matrix:
       TN= 90072  FP=  4928
       FN=  2632  TP=  2368
     [OK] Metrics saved -> /content/iot-anomaly-ml-service/app/../results/one-class_svm_metrics.txt
     [OK] Confusion matrix  -> /content/iot-anomaly-ml-service/app/../results/one-class_svm_confusion_matrix.png
  [OK] Time-series plot saved -> /content/iot-anomaly-ml-service/app/../results/one_class_svm_LogFloatValue_timeseries.png
  [OK] Score distribution   -> /content/iot-anomaly-ml-service/app/../results/one_class_svm_score_distribution.png
  [OK] Scatter plot         -> /content/iot-anomaly-ml-service/app/../results/one_class_svm_scatter.png

  -- K-Means --
     Total readings : 100000
     Normal         : 93029  (93.0%)
     Anomalies      : 6971  (7.0%)
     Score mean     : 3.8411
     Score std      : 2.9196

     -- K-Means: Supervised Metrics --
     Accuracy  : 0.9265
     Precision : 0.3312
     Recall    : 0.4618
     F1 Score  : 0.3858
     Confusion Matrix:
       TN= 90338  FP=  4662
       FN=  2691  TP=  2309
     [OK] Metrics saved -> /content/iot-anomaly-ml-service/app/../results/k-means_metrics.txt
     [OK] Confusion matrix  -> /content/iot-anomaly-ml-service/app/../results/k-means_confusion_matrix.png
  [OK] Time-series plot saved -> /content/iot-anomaly-ml-service/app/../results/k_means_LogFloatValue_timeseries.png
  [OK] Score distribution   -> /content/iot-anomaly-ml-service/app/../results/k_means_score_distribution.png
  [OK] Scatter plot         -> /content/iot-anomaly-ml-service/app/../results/k_means_scatter.png
  [OK] Comparison chart     -> /content/iot-anomaly-ml-service/app/../results/model_comparison.png

  -- Cross-Model Consensus --
     Points flagged by ALL 3 models: 3296

[4/5] Live data demo:
      /content/drive/MyDrive/data/live_data.csv
      Live rows: 50000
      Isolation Forest live anomalies: 2532 / 50000 (5.1%)

[5/5] Complete!

=================================================================
Traceback (most recent call last):
  File "/content/iot-anomaly-ml-service/train.py", line 203, in <module>
    main(args.train, args.test, args.live)
  File "/content/iot-anomaly-ml-service/train.py", line 192, in main
    print(f"  Models saved in: {os.path.join(BASE_DIR, 'saved_models')}")
                                             ^^^^^^^^
NameError: name 'BASE_DIR' is not defined. Did you mean: 'DATA_DIR'?

In [25]:
import os

if 'COLAB_GPU' in os.environ:
    DATA_DIR = "/content/drive/MyDrive/data"
else:
    BASE_DIR = os.path.dirname(os.path.abspath("__file__"))
    DATA_DIR = os.path.join(BASE_DIR, "..", "data")

In [26]:
print(DATA_DIR)
print(os.path.exists(DATA_DIR))

/content/drive/MyDrive/data
True

In [27]:
!git pull

remote: Enumerating objects: 5, done.
remote: Counting objects: 100% (5/5), done.
remote: Compressing objects: 100% (1/1), done.
remote: Total 3 (delta 2), reused 3 (delta 2), pack-reused 0 (from 0)
Unpacking objects: 100% (3/3), 277 bytes | 138.00 KiB/s, done.
From https://github.com/shaonkhalifa/iot-anomaly-ml-service
   07d601a..c4feee7  main       -> origin/main
Updating 07d601a..c4feee7
Fast-forward
 train.py | 3 ++-
 1 file changed, 2 insertions(+), 1 deletion(-)

In [28]:
import os

os.listdir('/content/iot-anomaly-ml-service/saved_models')

['kmeans.pkl',
 'one_class_svm.pkl',
 'scaler.pkl',
 'isolation_forest.pkl',
 'kmeans_threshold.pkl']

In [29]:
import joblib
import numpy as np

model = joblib.load("saved_models/isolation_forest.pkl")
scaler = joblib.load("saved_models/scaler.pkl")

sample = np.array([[10, 32.5, 14, 2, 0, 5,
                    1,0,0,0,0,
                    1,0,0,0,0,0,0,0,
                    0,0]])

sample_scaled = scaler.transform(sample)

result = model.predict(sample_scaled)

print("Prediction:", result)  # -1 = anomaly, 1 = normal

Prediction: [1]

In [32]:


import joblib
import numpy as np

model = joblib.load("saved_models/isolation_forest.pkl")
scaler = joblib.load("saved_models/scaler.pkl")

sample = np.array([[9999, 9999, 3, 6, 1, 9999,
                    0,0,0,0,1,
                    0,0,0,0,0,0,1,0,
                    1,1]])

sample_scaled = scaler.transform(sample)

result = model.predict(sample_scaled)

print("Prediction:", result)  # -1 = anomaly, 1 = normal

Prediction: [-1]

In [34]:


import joblib
import numpy as np

model = joblib.load("saved_models/isolation_forest.pkl")
scaler = joblib.load("saved_models/scaler.pkl")

sample = np.array([[5, 20.0, 3, 6, 1, 50000,
                    0,1,0,0,0,
                    0,1,0,0,0,0,0,0,
                    0,0]])

sample_scaled = scaler.transform(sample)

result = model.predict(sample_scaled)

print("Prediction:", result)  # -1 = anomaly, 1 = normal

Prediction: [1]

In [35]:
import os

folder = "/content/iot-anomaly-ml-service/saved_models"

for f in os.listdir(folder):
    path = os.path.join(folder, f)
    print(f, os.path.getsize(path) / 1024, "KB")

kmeans.pkl 1954.3505859375 KB
one_class_svm.pkl 464.0615234375 KB
scaler.pkl 1.0771484375 KB
isolation_forest.pkl 1415.4462890625 KB
kmeans_threshold.pkl 0.1142578125 KB

In [36]:
import shutil
import os

src = "/content/iot-anomaly-ml-service/saved_models"
dst = "/content/drive/MyDrive/ml-models"

os.makedirs(dst, exist_ok=True)

for file in os.listdir(src):
    shutil.copy(os.path.join(src, file), dst)

print("✅ Models copied to Google Drive")

✅ Models copied to Google Drive

In [37]:
!zip -r ml_models.zip /content/iot-anomaly-ml-service/saved_models

  adding: content/iot-anomaly-ml-service/saved_models/ (stored 0%)
  adding: content/iot-anomaly-ml-service/saved_models/kmeans.pkl (deflated 95%)
  adding: content/iot-anomaly-ml-service/saved_models/one_class_svm.pkl (deflated 92%)
  adding: content/iot-anomaly-ml-service/saved_models/scaler.pkl (deflated 14%)
  adding: content/iot-anomaly-ml-service/saved_models/isolation_forest.pkl (deflated 74%)
  adding: content/iot-anomaly-ml-service/saved_models/kmeans_threshold.pkl (deflated 12%)

In [38]:
from google.colab import files
files.download("ml_models.zip")